#!/bin/sh

rsync -rav --delete \
	--exclude '.*' \
	--exclude node_modules \
	. 'enceladus:~/db-hafas-rest/'

ssh enceladus "\
cd ~/db-hafas-rest
npm i
npm update
forever stop db-hafas-rest
forever start -a --uid db-hafas-rest index.js"
